### PR TITLE
Update peer ID for Obscura

### PR DESCRIPTION
**Pull request by FilipHarald**
Old peer ID got lost during upgrade.

### CODE REVIEW

**Comment by georgeee** [comment]
PR needs rebase upon updated base branch (one more seed was added as the first line)

**Comment by georgeee** [comment]
@FilipHarald could you check that node `/dns4/mina-mainnet-seed.obscura.network/tcp/5002/p2p/12D3KooWGfz8BNh9BYCifPAyV9jt9P7nutmt4VXQvs94woFshqMJ` is up and synced. I can connect to it via telnet, but when I run test (as described [here](https://gist.github.com/georgeee/d6b90efc6c4556ee971f445645e21ded)) for a Mina ndoe to synchronizze to the network using the seed node, my test still fails.

**Comment by FilipHarald** [comment]
> @FilipHarald could you check that node `/dns4/mina-mainnet-seed.obscura.network/tcp/5002/p2p/12D3KooWGfz8BNh9BYCifPAyV9jt9P7nutmt4VXQvs94woFshqMJ` is up and synced? I can connect to it via telnet, but when I run test (as described [here](https://gist.github.com/georgeee/d6b90efc6c4556ee971f445645e21ded)) for a Mina ndoe to synchronizze to the network using the seed node, my test still fails.

Ah, yes, will do! I was using this script, I see now that it's not a complete check: https://github.com/MinaFoundation/seeds/blob/main/scripts/check-seeds.sh

**Review by simisimis — APPROVED** [review]
lgtm

**Comment by FilipHarald** [comment]
I'm pretty sure I found the problem @georgeee :sweat_smile: 

I'm running devnet in same docker-compose and accidentally mixed the two when I did the PR.

But troubleshooting this helped me see that the peer ID also got renewed for the devnet-node when upgrading. Now I've tested as well. I didn't use your script but just started a node with only one entry in seed-node list. :+1:

**Review by georgeee — APPROVED** [review]
Didn't test devnet.txt change, but mainnet.txt change fixed the issue and synchronization test was successful on my side.

**Review by johnmarcou — APPROVED** [review]
LGTM

**Pull request merged**
